apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-1
    app.kubernetes.io/part-of: purple-mermaid
  name: nodejs-1
  namespace: rorai
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-1
    weight: 100
status: {}
